version: 2.6.{build}
os: Visual Studio 2017
configuration: Release
environment:
  clone_folder: c:\gs
  GITHUB_REPO_TOKEN:
    secure: Jmpeow5aAcDhUHkwac/AC6MzQciGc9TLgrp5oz4U0gyAwCWGqqxJhmjz3AVrWp/V	
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
install:
- cmd: choco install gtksharp
  
before_build:
- cmd: dotnet --version

build_script:
- ps: .\build.ps1

after_build:
# Build the GeneticSharp and GeneticSharp.Extensions NuGet packages.
- ps: .\tools\buildLibrariesNuget.cmd

# Build the GeneticSharp.Templates NuGet package.
- ps: .\tools\buildTemplatesNuget.cmd

artifacts:
  - path: .\src\nuget\*.nupkg
    name: Libraries NuGet packages

  - path: .\src\Templates\*.nupkg
    name: Templates NuGet package