version: 2.5.{build}
os: Visual Studio 2017
configuration: Release
environment:
  clone_folder: c:\gs
  COVERALLS_REPO_TOKEN:
    secure: O/w+gFTqDriJlktWz0p4xJbT0RnDfj8NZsVAShy54prPmxKEBDBGKwt8S4heGOcq
  GITHUB_REPO_TOKEN:
    secure: Jmpeow5aAcDhUHkwac/AC6MzQciGc9TLgrp5oz4U0gyAwCWGqqxJhmjz3AVrWp/V	
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
install:
- cmd: choco install gtksharp
  
before_build:
- cmd: dotnet --version
- cmd: dotnet restore src

build_script:
# The default build
- cmd: dotnet build src -c release

# All projects support net462 (GTK# only support net462)
- cmd: dotnet build src -c release -f net462

# Libraries support .netstandard2.0
- cmd: dotnet build src/GeneticSharp.Domain -f netstandard2.0
- cmd: dotnet build src/GeneticSharp.Extensions -f netstandard2.0
- cmd: dotnet build src/GeneticSharp.Infrastructure.Framework -f netstandard2.0

# Unit tests and ConsoleApp support .netcoreapp2.0
- cmd: dotnet build src/GeneticSharp.Domain.UnitTests -f netcoreapp2.0
- cmd: dotnet build src/GeneticSharp.Extensions.UnitTests -f netcoreapp2.0
- cmd: dotnet build src/GeneticSharp.Infrastructure.Framework.UnitTests -f netcoreapp2.0
- cmd: dotnet build src/GeneticSharp.Runner.ConsoleApp -f netcoreapp2.0

after_build:
# Build the GeneticSharp and GeneticSharp.Extensions NuGet packages.
- cmd: >-   
    mkdir .\src\nuget
    dotnet pack src/GeneticSharp.Domain/GeneticSharp.Domain.csproj -c release --no-build --output ../nuget /p:PackageVersion=2.5.0
    dotnet pack src/GeneticSharp.Extensions/GeneticSharp.Extensions.csproj -c release --no-build --output ../nuget /p:PackageVersion=2.5.0

# Build the GeneticSharp.Templates NuGet package.
- cmd: >-   
    cd .\src\Templates
    nuget pack -Version 1.0.0
    dotnet new -i GeneticSharp.Templates.1.0.0.nupkg

    # GeneticSharpConsoleApp
    dotnet new GeneticSharpConsoleApp -n ConsoleApp -o ConsoleApp
    dotnet build ConsoleApp/ConsoleApp.csproj # We don't run it, because this templates throw an exception asking to programmer to implement the Chromomosome representation.

    # GeneticSharpTspConsoleApp
    dotnet new GeneticSharpTspConsoleApp -n TspConsoleApp -o TspConsoleApp
    dotnet run TspConsoleApp/TspConsoleApp.csproj

    # GeneticSharpTspUnity3d
    dotnet new GeneticSharpTspUnity3d -n TspUnity3d -o TspUnity3d
    # We don't build this template, because it needs Unity3d installed.

test_script:
- cmd: dotnet clean src/GeneticSharp.Domain.UnitTests
- cmd: dotnet test src/GeneticSharp.Domain.UnitTests -f netcoreapp2.0

- cmd: dotnet clean src/GeneticSharp.Extensions.UnitTests
- cmd: dotnet test src/GeneticSharp.Extensions.UnitTests -f netcoreapp2.0

- cmd: dotnet clean src/GeneticSharp.Infrastructure.Framework.UnitTests
- cmd: dotnet test src/GeneticSharp.Infrastructure.Framework.UnitTests -f netcoreapp2.0

artifacts:
  - path: .\src\nuget\*.nupkg
    name: Libraries NuGet packages

  - path: .\src\Templates\*.nupkg
    name: Templates NuGet package