version: 1.2.{build}
os: Visual Studio 2017
configuration: Release
environment:
  clone_folder: c:\gs
  COVERALLS_REPO_TOKEN:
    secure: O/w+gFTqDriJlktWz0p4xJbT0RnDfj8NZsVAShy54prPmxKEBDBGKwt8S4heGOcq
  GITHUB_REPO_TOKEN:
    secure: Jmpeow5aAcDhUHkwac/AC6MzQciGc9TLgrp5oz4U0gyAwCWGqqxJhmjz3AVrWp/V	
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
install:
- cmd: choco install gtksharp    

nuget:
  account_feed: true
  project_feed: true
  
before_build:
- cmd: dotnet --version
- cmd: dotnet restore src

build_script:
# The default build
- cmd: dotnet build src -c release

# All projects support net462 (GTK# only support net462)
- cmd: dotnet build src -c release -f net462

# Libraries support .netstandard2.0
- cmd: dotnet build src/GeneticSharp.Domain -f netstandard2.0
- cmd: dotnet build src/GeneticSharp.Extensions -f netstandard2.0
- cmd: dotnet build src/GeneticSharp.Infrastructure.Framework -f netstandard2.0

# Unit tests and ConsoleApp support .netcoreapp2.0
- cmd: dotnet build src/GeneticSharp.Domain.UnitTests -f netcoreapp2.0
- cmd: dotnet build src/GeneticSharp.Extensions.UnitTests -f netcoreapp2.0
- cmd: dotnet build src/GeneticSharp.Infrastructure.Framework.UnitTests -f netcoreapp2.0
- cmd: dotnet build src/GeneticSharp.Runner.ConsoleApp -f netcoreapp2.0

after_build:
- cmd: >-   
    mkdir .\src\nuget

    dotnet pack src/GeneticSharp.Domain/GeneticSharp.Domain.csproj -c release --no-build /p:PackageVersion=%APPVEYOR_BUILD_VERSION% --output .\src\nuget

test_script:
- ps: >-
    .\tools\OpenCover\tools\OpenCover.Console.exe -skipautoprops -target:"dotnet.exe" "-targetargs: test src\GeneticSharp.Domain.UnitTests --framework netcoreapp2.0 -c release" -register:user -oldStyle -output:opencoverCoverage.xml -filter:"+[GeneticSharp.Domain]* +[GeneticSharp.Extensions]* +[GeneticSharp.Infrastructure.Framework]*" 
- ps: >-
    .\tools\coveralls\tools\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
artifacts:
  - path: .\src\nuget\*.nupkg
    name: NuGet packages
